### DISCUSSION TITLE
2024/04/07/Hexo-giscus%E9%85%8D%E7%BD%AE%E8%AF%84%E8%AE%BA%E5%8A%9F%E8%83%BD/

### DISCUSSION THREAD

**Discussion by giscus** [CasonMo/comment-utterances#11] [Announcements]
# 2024/04/07/Hexo-giscus%E9%85%8D%E7%BD%AE%E8%AF%84%E8%AE%BA%E5%8A%9F%E8%83%BD/

注意：本文以Fluid主题当示例来介绍如何配置评论，其他主题请根据对应用户手册配置  Giscus 允许你将 GitHub Discussions 集成到你的网站上作为评论系统。这样做的好处是评论数据存储在 GitHub 上，不需要第三方服务。 官方地址：https://giscus.app/  首先先看看自己的theme/fluid下是否包含giscus相关的文件，如果fluid版本

https://casonmo.github.io/2024/04/07/Hexo-giscus%E9%85%8D%E7%BD%AE%E8%AF%84%E8%AE%BA%E5%8A%9F%E8%83%BD/

**Comment by comkeps** [comment]
hello

**Reply by CasonMo** [reply]
hello

**Reply by comkeps** [reply]
你好呀，按照步骤配置的没成功。试了好多插件了，请问可能哪里出了问题呢

**Reply by comkeps** [reply]
第二步说的新建一个GitHub仓库，是指博客所在的仓库，还是另外重新建一个

**Reply by CasonMo** [reply]
用的什么主题，和我一样的吗

**Reply by comkeps** [reply]
对的fluid

**Reply by CasonMo** [reply]
新建一个仓库，专门用来存储评论

**Reply by comkeps** [reply]
行，我再试一下，谢啦

**Reply by CasonMo** [reply]
你根据我的流程配置，一定可以的，注意里面的一些参数替换成自己的就行了

**Reply by comkeps** [reply]
最后一步  “注意：以前用Utterances的可以把github issue 转成discussion”
是什么意思，需要配置这一步吗，以前配置过Utterances但是没生效。

**Reply by comkeps** [reply]
还是不行，很奇怪，之前试了很多插件也不行，毫无反应。是不是config.yml哪里配置有问题？可是我都是按照步骤来的啊  》_《

**Reply by CasonMo** [reply]
最后一步不用管 那些是之前使用utterances的 切换成discussion的

**Reply by comkeps** [reply]
嗯，可还是不行。。

**Reply by CasonMo** [reply]
这个文档你有看吗？https://giscus.app/zh-CN 里面有教你怎么获取repo-id等等参数
如果说你已经正确安装了giscus ， 那就重点检查一点配置对不对
```
giscus:
  repo: 这里替换成仓库名字 例如CasonMo/comment
  repo-id: 参考文档https://giscus.app/zh-CN
  category: Announcements
  category-id: 参考文档https://giscus.app/zh-CN
  # Available values: pathname | url | title | og:title
  mapping: pathname
  # Available values: 0 | 1
  reactions-enabled: 1
   # Available values: 0 | 1
  emit-metadata: 0
  # Available values: light | dark | dark_high_contrast | transparent_dark | preferred-color-scheme
  theme: preferred_color_scheme
  # Available values: en | zh-CN
  lang: zh-CN
  # Place the comment box above the comments
  input-position: top
```
